# Generated by Django 3.1.4 on 2020-12-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='interfaces',
            field=models.ManyToManyField(to='vlan.Interfaces'),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='number',
            field=models.CharField(max_length=5, verbose_name='Number'),
        ),
    ]
