# Generated by Django 3.1.4 on 2020-12-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlan', '0002_auto_20201219_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='gateway',
            field=models.CharField(blank=True, max_length=40, verbose_name='Gateway'),
        ),
    ]
